FROM alpine:3.4

ENV GOPATH /go
ENV CGO_ENABLED 0

RUN apk add --update -t build-deps go bash \
 && rm -rf /var/cache/apk/* \
 && mkdir -p /go/src/github.com/kelseyhightower/confd \
 && ln -s /go/src/github.com/kelseyhightower/confd /app

WORKDIR /app
